"""empty message

Revision ID: 810df8b7ff38
Revises: 9af46f0501f8
Create Date: 2024-01-18 01:22:59.856257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810df8b7ff38'
down_revision = '9af46f0501f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
